apiVersion: v1
kind: Service
metadata:
  name: voice-api-staging
  namespace: staging
  labels:
    app: voice-api-staging
  annotations:
    cloud.google.com/backend-config: '{"default": "voice-api-staging-backend"}'
spec:
  type: NodePort
  selector:
    app: voice-api-staging
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: voice-api-staging-backend
  namespace: staging
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 300
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 3600
  healthCheck:
    checkIntervalSec: 10
    port: 3000
    type: HTTP
    requestPath: /health
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-api-staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: voice-api-staging-ip
    networking.gke.io/managed-certificates: voice-api-staging-cert
spec:
  defaultBackend:
    service:
      name: voice-api-staging
      port:
        number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: voice-api-staging-cert
  namespace: staging
spec:
  domains:
    - staging.voiceapi.0ptive.com
